### ISSUE TITLE
Update tailscale to 1.48.0

### ISSUE THREAD

**Issue by subract** [giodamelio/tailscale-custom-domain-dns#15]
Please update the tailscale dependency when you get a chance. The current version has some incompatibility with tailnet locks. Hopefully it's a drop-in upgrade.

Also, huge thank-you for putting this project together. I share your concern about vendor lock-in, and I find your solution an elegant way of dealing with the issue.

**Comment by giodamelio** [comment]
Thanks for the kind words! I will do a upgrade tomorrow.

**Comment by giodamelio** [comment]
I just released [v0.6.4](https://github.com/giodamelio/tailscale-custom-domain-dns/releases/tag/v0.6.4), with the updated Tailscale!

**Comment by subract** [comment]
Much appreciated, thank you!
